### ISSUE TITLE
#100! 

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#100]
YAY!!

**Comment by CubeyTheCube** [comment]
this is a very good issue thanks

**Comment by retronbv** [comment]
2021 100% no scam free vbucks just comment on this issue

**Comment by CubeyTheCube** [comment]
> 2021 100% no scam free vbucks just comment on this issue

yes please

**Comment by retronbv** [comment]
> > 2021 100% no scam free vbucks just comment on this issue
> 
> yes please

ok dming you on discord

**Comment by Explosion-Scratch** [comment]
#100

**Comment by retronbv** [comment]
> #100 (beat u to it retron)

uhh

**Comment by Explosion-Scratch** [comment]
> > #100 (beat u to it retron)
> 
> uhh

bc you commented on #200 and #300 😐

**Comment by retronbv** [comment]
oh
