### ISSUE TITLE
IE Literally does not work with the website.

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#106]
We need to fix this! :stuck-out-tongue:
Test ID: TES1009631481614879563876401
Test URL: https://bijou.js.org
Operating System: Windows 10
Browser: IE 11
Resolution: 1024x768

https://s3.amazonaws.com/issues-screenshots/oYzrDjFNq1l49Vdx8qIFps3TwsJxUhWYeACllvxL1614880031.png

**Comment by wgyt** [comment]
Who uses IE?
And why?

**Comment by Touchcreator** [comment]
Who cares, even my grandma doesnt use IE

**Comment by GrahamSH-LLK** [comment]
The problem is that js_Load never fires

**Comment by Explosion-Scratch** [comment]
> The problem is that js_Load never fires

I see. I really don't care about IE users though, they can switch to a different browser.
