### ISSUE TITLE
[Website] Allow users to opt out of analytics 

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#109]
Currently it does this when users view [bijou.js.org](https://bijou.js.org)
![image](https://user-images.githubusercontent.com/61319150/110040410-60ab9500-7d08-11eb-8c16-13c17bb09741.png)
We should allow opt-out

**Comment by TheColaber** [comment]
There's really 3 options:
1) Not have any at all
2) Just have an ad blocker (maybe?)
3) Actually allow opting out.

**Comment by Explosion-Scratch** [comment]
> There's really 3 options:
> 
> 1. Not have any at all

No, it's cool.

> 2. Just have an ad blocker (maybe?)

Ad blockers don't protect loading 1x1 pixel images 😜 

> 3. Actually allow opting out.

Yeah, this.

**Comment by retronbv** [comment]
How would we allow opting out? Should we store something in local storage? Then it won't load the image if there is the key in local storage

**Comment by Explosion-Scratch** [comment]
> How would we allow opting out? Should we store something in local storage? Then it won't load the image if there is the key in local storage

Yep. LocalStorage.

**Comment by retronbv** [comment]
(Is someone going to do this or should I)

**Comment by Explosion-Scratch** [comment]
> (Is someone going to do this or should I)

I'm just going to remove analytics.

**Comment by retronbv** [comment]
Nooooooooooooo
