### ISSUE TITLE
One Single Export

### ISSUE THREAD

**Issue by TheColaber** [Bijou-js/Bijou.js#110]
For a neater file.

**Comment by CubeyTheCube** [comment]
what an issue

**Comment by Explosion-Scratch** [comment]
But then how would we do this:
```js
import {aSingleFunction as litterallyAnything} from "bijou.js"
```

**Comment by TheColaber** [comment]
Hmm... lemme research.

**Comment by TheColaber** [comment]
Hmm, I guess you can't. What a bummer.

**Comment by Explosion-Scratch** [comment]
@all-contributors add @TheColaber for bugs code and docs

**Comment by Explosion-Scratch** [comment]
@all-contributors add @thecoder876 for bug fixes
