### ISSUE TITLE
[Bug] Shoot error for missing params

### ISSUE THREAD

**Issue by TheColaber** [Bijou-js/Bijou.js#111]
Instead of errors like these:
![image](https://user-images.githubusercontent.com/72760579/110042863-6a3afa00-7d14-11eb-9f82-da4f45178ceb.png)
It should produce a custom error like: "Missing Param 'Text'."

**Comment by CubeyTheCube** [comment]
```js
export let capitalize = (str) => {
  if(!str) throw new TypeError("Missing Param 'Str'.");
  return String.fromCodePoint(str.codePointAt(0)).toUpperCase() +
  str.slice(str.codePointAt(0) > 0xffff ? 2 : 1);
}
``` 
speaking of `capitalize`, imo it should convert the whole string to title case, not just the first letter.

**Comment by Explosion-Scratch** [comment]
> ```js
> export let capitalize = (str) => {
>   if(!str) throw new TypeError("Missing Param 'Str'.");
>   return String.fromCodePoint(str.codePointAt(0)).toUpperCase() +
>   str.slice(str.codePointAt(0) > 0xffff ? 2 : 1);
> }
> ```
> 
> speaking of `capitalize`, imo it should convert the whole string to title case, not just the first letter.

Good idea.

**Comment by Explosion-Scratch** [comment]
Both things implemented.
