### ISSUE TITLE
[Feature request] $_.capitalize should only change first letter, and there should be a new function that converts a string to title case.

### ISSUE THREAD

**Issue by CubeyTheCube** [Bijou-js/Bijou.js#115]
$_.capitalize should just capitalize the first letter of a string, and there should be a new function called $\_.titleCase that converts a whole string to title case, like this:

```js
/**
 * Converts a string to title case
 * @memberOf bijou
 * @function
 * @param {String} str The string to convert to title case.
 * @example
 * _$.titleCase("hello world");//Returns "Hello World"
 * @returns {String} The string in title case.
 */
export let titleCase = (str) =>
    str.toLowerCase().split(" ").map((word, index) => 
    ["at", "by", "for", "in", "of", "off", "on", "out", "to", "up", "as", "if", "but", "per", "via", "for", "and", "nor", "but", "or", "yet", "so", "the", "a", "an"].includes(word) && index != 0 ? word : String.fromCodePoint(word.codePointAt(0)).toUpperCase() + word.slice(word.codePointAt(0) > 0xFFFF ? 2 : 1))
    .join(" ");
```

**Comment by CubeyTheCube** [comment]
> Hi there! Welcome to Bijou.js! We appreciate you contributing to this project! Someone will look over your issue shortly! In the meantime you can take a look at our [website](https://bijou.js.org) to learn more about this project!
> This message is automated

You know, I looked in my bedroom, I looked in my kitchen, I looked in my backyard, I looked in my school, and I looked in my refrigerator, but I couldn't find a single person who asked!

**Comment by ChaoticRaccoon** [comment]
> > Hi there! Welcome to Bijou.js! We appreciate you contributing to this project! Someone will look over your issue shortly! In the meantime you can take a look at our [website](https://bijou.js.org) to learn more about this project!
> > This message is automated
> 
> You know, I looked in my bedroom, I looked in my kitchen, I looked in my backyard, I looked in my school, and I looked in my refrigerator, but I couldn't find a single person who asked!

Look in the sky, I bet maybe the CIA or mars rover knows who asked
