### ISSUE TITLE
[Feature request] Make it easier to edit

### ISSUE THREAD

**Issue by wgyt** [Bijou-js/Bijou.js#127]
To make Bijou.JS easier to edit break the functions in to multiple files. When we compile Bijou, add all of the code to one file

**Comment by Explosion-Scratch** [comment]
It's a good idea but I feel like it has several downsides:
1) Hard to keep track of
2) Harder to compile (JSDocs might be a big problem)
3) I still have that huge file :P, and who is gonna do this? I can't without a code editor 😭 

Advantages:
4) Code is better organized and easier to find functions in
5) I might be able to work on this project again.


In short if you make a PR, I'll merge it.
