### ISSUE TITLE
[Bug] mapString's code is bad

### ISSUE THREAD

**Issue by CubeyTheCube** [Bijou-js/Bijou.js#132]
currently the code for _$.mapString is this
```js
export let mapString = (str, fn) =>
  str
    .split('')
    .map((c, i) => fn(c, i, str))
    .join('');
```
but array#map takes a function as a parameter!!!!
so it should just be this
```js
export let mapString = (str, fn) =>
  str
    .split('')
    .map(fn)
    .join('');
```
even better,
```js
export let mapString = (str, fn) =>
  [...str]
    .map(fn)
    .join('');
```
and if you want it to be faster,
```js
export let mapString = (str, fn) =>
  Array.prototype.map.call(str, fn).join('')
```

~~also this repo needs a code quality issue category~~

**Comment by CubeyTheCube** [comment]
@Explosion-Scratch I tested it on jsbench and apparently the second to last code snippet is the fastest.

**Comment by Explosion-Scratch** [comment]
@all-contributors add @CubeyTheCube for code

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for Code

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for design

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for bug fixes

**Comment by retronbv** [comment]
@all-contributors please add @retronbv for code, ideas, bug fixes
