### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#164]

**Comment by Explosion-Scratch** [comment]
@all-contributors add @apple502j for security

**Comment by Explosion-Scratch** [comment]
@all-contributors add @GrahamSH-LLK for bug fixes, code and docs

**Comment by retronbv** [comment]
@all-contributors add @retronbv for docs

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for docs code bug fixes website development @GrahamSH-LLK for bug fixes docs and development

**Comment by Explosion-Scratch** [comment]
@all-contributors add @GrahamSH-LLK for bug fixes docs and web development

**Comment by Explosion-Scratch** [comment]
@all-contributors add @pufferfish101007 for bug fixes docs

**Comment by retronbv** [comment]
ARE YOU OKAY????

**Comment by Explosion-Scratch** [comment]
me?

**Comment by Explosion-Scratch** [comment]
yes

**Comment by Explosion-Scratch** [comment]
@all-contributors add @devxan for docs and bugs

**Comment by retronbv** [comment]
you aren’t responding. Get on discord

**Comment by Explosion-Scratch** [comment]
oh sorry retron

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for infrastructure and tests

**Comment by Explosion-Scratch** [comment]
@all-contributors add @pufferfish101007 for tests

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Touchcreator for bugs
