### ISSUE TITLE
Who wants to help? And with what?

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#17]
If any of you guys have _any_ ideas for this project please comment! I'd like this project to continue expanding but I am at a loss for ideas! What else would make this better?

**Comment by D1WK** [comment]
I wanna help, here's a snippet I have(for JS noobs)
```function draw() {  
      
    background(220);  
      
    // Use color() function  
    let c = color('green');  
  
    // Use fill() function to fill color  
    fill(c);  
      
    // Draw a rectangle  
    rect(50, 50, 300, 200);  
      
} ```

**Comment by D1WK** [comment]
I don't know how to edit the snippets tho, help

**Comment by Explosion-Scratch** [comment]
> I wanna help, here's a snippet I have(for JS noobs)

Sorry but that's very specific and I frankly don't see many cases where this would be useful. If you can generalize this though that might be helpful!

**Comment by D1WK** [comment]
> > I wanna help, here's a snippet I have(for JS noobs)
> 
> Sorry but that's very specific and I frankly don't see many cases where this would be useful. If you can generalize this though that might be helpful!

wdym?

**Comment by Explosion-Scratch** [comment]
> I don't know how to edit the snippets tho, help

In bijou.js add a new property to the end of the _temp object with the function, like this:
```js
let _temp = {
   //Some stuff here
   yourFunction: (string) => {
      console.log(string);
  }
}
``` 
Now you can use it like this:
```js
_$.yourFunction("Hello");
```

**Comment by D1WK** [comment]
> > I wanna help, here's a snippet I have(for JS noobs)
> 
> Sorry but that's very specific and I frankly don't see many cases where this would be useful. If you can generalize this though that might be helpful!

Do you mean remove the values?

**Comment by Explosion-Scratch** [comment]
> > > I wanna help, here's a snippet I have(for JS noobs)
> > 
> > 
> > Sorry but that's very specific and I frankly don't see many cases where this would be useful. If you can generalize this though that might be helpful!
> 
> Do you mean remove the values?

🤔 Not really, what are several use cases of this function?

**Comment by D1WK** [comment]
> > > > I wanna help, here's a snippet I have(for JS noobs)
> > > 
> > > 
> > > Sorry but that's very specific and I frankly don't see many cases where this would be useful. If you can generalize this though that might be helpful!
> > 
> > 
> > Do you mean remove the values?
> 
> 🤔 Not really, what are several use cases of this function?

Making animations or art in JS, like I do.

**Comment by D1WK** [comment]
Also I barely know JS, I know a lot of HTML however.

**Comment by Explosion-Scratch** [comment]
whoops

**Comment by D1WK** [comment]
lol

**Comment by D1WK** [comment]
So if you need me, know i'm bad at JS but I can improve the site if you want.

**Comment by D1WK** [comment]
>yep okay then
Okay sir

**Comment by D1WK** [comment]
hehe
