### ISSUE TITLE
I can't access and edit

### ISSUE THREAD

**Issue by ZI-Youtuber** [Bijou-js/Bijou.js#180]
I can't access and edit the code even though I am a member of the organization

**Comment by Explosion-Scratch** [comment]
You're supposed to fork it to make changes, then make a PR, that way nobody accidentally messes something up. Only I, retronbv and GrahamSH-LLK have direct edit access.

**Comment by Explosion-Scratch** [comment]
> Hi there! Welcome to Bijou.js! We appreciate you contributing to this project! Someone will look over your issue shortly! In the meantime you can take a look at our [website](https://bijou.js.org) to learn more about this project!
> This message is automated

Shhh I already said hi before

**Comment by ZI-Youtuber** [comment]
ok

**Comment by retronbv** [comment]
> Hi there! Welcome to Bijou.js! We appreciate you contributing to this project! Someone will look over your issue shortly! In the meantime you can take a look at our [website](https://bijou.js.org) to learn more about this project!
> This message is automated

estupido

**Comment by AwayFromKeyword** [comment]
> Hi there! Welcome to Bijou.js! We appreciate you contributing to this project! Someone will look over your issue shortly! In the meantime, you can take a look at our [website](https://bijou.js.org) to learn more about this project!
> This message is automated

Ultimate bruh moment
