### ISSUE TITLE
Code Editor for Website

### ISSUE THREAD

**Issue by ZI-Youtuber** [Bijou-js/Bijou.js#182]
@Bijou-js/feature-finders 

A feature request for making a code editor inside the website if that is possible so people can test the snippets of code.

It can be like the one in w3schools you know like this: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_styles_intro

**It is my idea and I am in the team of Feature Finders**

I hope my idea will make the website better

**Comment by ZI-Youtuber** [comment]
> /try

So is it a good idea?

**Comment by GrahamSH-LLK** [comment]
I meant go to /try

**Comment by ZI-Youtuber** [comment]
where is that?

**Comment by ZI-Youtuber** [comment]
I don't know where that is

**Comment by GrahamSH-LLK** [comment]
AAH I mean https://bijou.js.org/try

**Comment by ZI-Youtuber** [comment]
there's nothing there

**Comment by ZI-Youtuber** [comment]
oh i get it

**Comment by ZI-Youtuber** [comment]
but not a good place to put a code editor

**Comment by ZI-Youtuber** [comment]
you should put it next to the code snipet

**Comment by ZI-Youtuber** [comment]
and put that code in and people can review the code

**Comment by ZI-Youtuber** [comment]
like this: https://www.w3schools.com/html/html_styles.asp

**Comment by ZI-Youtuber** [comment]
@GrahamSH-LLK

**Comment by GrahamSH-LLK** [comment]
There's a code editor at https://bijou.js.org/try, that's enough
