### ISSUE TITLE
Contributing file issues

### ISSUE THREAD

**Issue by pufferfish101007** [Bijou-js/Bijou.js#186]
- seeing as you're assuming there will only be functions, `@function` should be recommended to add.
- recursive fn example is incorrect, fairly sure it should be `let recursiveFunc = _recursive () => {}` or smth

**Comment by ZI-Youtuber** [comment]
@Explosion-Scratch @GrahamSH-LLK Can handle that I think

**Comment by Explosion-Scratch** [comment]
D'oh lol thanks

**Comment by Explosion-Scratch** [comment]
@all-contributors add @pufferfish101007 for docs and bugs

**Comment by Explosion-Scratch** [comment]
@all-contributors add @GrahamSH-LLK for infrastructure bug doc code
