### ISSUE TITLE
Pls can i join

### ISSUE THREAD

**Issue by ZI-Youtuber** [Bijou-js/Bijou.js#188]
Pls can I join the organization?

pls

**Comment by ZI-Youtuber** [comment]
@Explosion-Scratch @GrahamSH-LLK

**Comment by retronbv** [comment]
We have already invited you?

**Comment by ZI-Youtuber** [comment]
it kicked me out

**Comment by ZI-Youtuber** [comment]
can you add me back pls?

**Comment by ZI-Youtuber** [comment]
@retronbv

**Comment by retronbv** [comment]
Please stop spamming

**Comment by retronbv** [comment]
I have blocked @ZI-Youtuber from the org for one day. Any objections? Email me at `yourmom@gay.com`

**Comment by GrahamSH-LLK** [comment]
> I have blocked @ZI-Youtuber from the org for one day. Any objections? Email me at `yourmom@gay.com`

I have no objections.
