### ISSUE TITLE
Running the git-bat workflow from workflow_dispatch does not work.

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#19]
This is because it is conditional on whether the most recent commit message has "[Actions]" in it, therefore running it from `workflow_dispatch` does not work. 

#### Solutions:
1: Create another workflow
2: Run something different in the same workflow using conditionals (I have no idea how to do this)
3: Scrap it and just commit something random with `[Actions]` in the title.

**Comment by GrahamSH-LLK** [comment]
How about checking if _either_ it has actions, or if something is defined from the workflow_dispatch?

**Comment by Explosion-Scratch** [comment]
Hmm good idea.

**Comment by Explosion-1** [comment]
Hmm

**Comment by D1WK** [comment]
Hmmmmm, GitHub actions is a bit tricky.

**Comment by Explosion-Scratch** [comment]
This is actually pointless. I don't actually ever need to run it from workflow_dispatch anyways
