### ISSUE TITLE
[Feature request] Use object shorthand property notation to export 

### ISSUE THREAD

**Issue by pufferfish101007** [Bijou-js/Bijou.js#191]
**Is your feature request related to a problem? Please describe.**
This is a clear and concise description of what the problem is. I'm always frustrated when I'm looking at all the functions/objects available in `bijou.js` or j`s/_end.js` because I like looking at the source code rather than docs, and it's unnecessarily long IMO to have things like `{...browser: browser...}` when it could just be `{... browser...}` , making it far easier to read, especially as most, if not all, functions/objects have the same name when exported as when defined

**Describe the solution you'd like**
There is a clear and concise description of what you want to happen above.

**Describe alternatives you've considered**
You could keep it as it is but I'd be very sad :(

**Additional context**
I'm making a discord bot that will hopefully include lots if bijou functions because why not, and so I was trying to copy a list of all functions to then filter.

**Comment by pufferfish101007** [comment]
Thanks :D

**Comment by Explosion-Scratch** [comment]
np
