### ISSUE TITLE
[Website problem] The scrollbars look ugly

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#210]
![image](https://user-images.githubusercontent.com/61319150/115157902-4415b300-a051-11eb-8b25-a39cfe48e213.png)

**Comment by Explosion-Scratch** [comment]
@all-contributors add @AwayFromKeyword for deleted

**Comment by Explosion-Scratch** [comment]
@all-contributors add @AwayFromKeyword for custom

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for content

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for example

**Comment by retronbv** [comment]
Whyyy use multiple issues 😔 my notifs now be spammed

**Comment by Explosion-Scratch** [comment]
> Whyyy use multiple issues 😔 my notifs now be spammed

Sorry retron
