### ISSUE TITLE
Posted from discord

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#32]
This issue will have the messages posted from discord

**Comment by Explosion-Scratch** [comment]
Author: --Explosion--
Content:
    Test

**Comment by YOYITsM3M8** [comment]
How does that work

**Comment by Explosion-Scratch** [comment]
Post in the discord channel

**Comment by YOYITsM3M8** [comment]
Ok

**Comment by Explosion-Scratch** [comment]
Test

**Comment by Explosion-Scratch** [comment]
Test

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Test

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Test

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Test

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Ik

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
its posting as you

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
idk dood

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Huh

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
its showing up in <#800036763019509790> but not on the github yet

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
https://github.com/Bijou-js/Bijou.js/issues/32#issuecomment-765407236

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
>:)

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
yea

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
That'd be recursion, right?

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
(What if I set it up to repost the comments in the github channel)

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
OMG IT WORKS!!!

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
<#800036763019509790>

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
did it work

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
What

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
WOAH

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
> 802173054901026836
oof

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
wait how do it

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
booo

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
802172918791405638
oof

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
bad nqn

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
no nqn

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
ima bot???

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
whow

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
it's stil on

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
OH NOES

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
spamy will not be good

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
spamy will not be good

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
spamy will not be good

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
spamy will not be good

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
spamy will not be good

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
its in a different order

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Okay we get it

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
😎

**Comment by Explosion-Scratch** [comment]
retronbv wrote:

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
📉

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
😁

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
🆘

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
ik

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
its in the wrong ordr

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
🥉  Testing emojis

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
This is really cool tho

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
lol

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
👍

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
WOW

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
i said dat

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
i got a link for a post and pasted it

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
https://github.com/Bijou-js/Bijou.js/issues/32

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
This posts to github!!!

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
I know

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
how did you do dat

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
dat not fair

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
😦

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
haha

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
im still imune

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
nooo

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
lol

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
da

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
me too

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
You're immune?

**Comment by Explosion-Scratch** [comment]
retronbv wrote:

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Ik

**Comment by Explosion-Scratch** [comment]
retronbv wrote:

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
hehehe

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
"Slowmode is enabled, but you are immune. Amazing!"

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
lol

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Sorry

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
nooooooooooo

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Slowwwwmoooode

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
6 hour slowmode noobs

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
<@!756564712589885503> not fair I should be mod

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
hehe

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
WHooooopssss

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
no

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Is it slowmode still

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
this is gonna kill peoples github notif feed

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
oof

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
¯\_(ツ)_/¯

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Stop please

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
NOOOOOOBBBBS

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Lol

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
😭

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
test

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
i wont my dudette

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Don't spam

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Only 2 minute slow mode

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Yeah, the order of messages is messed up

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
DUDETTE??! I am a DUDE in the most macho way possible

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
<https://www.youtube.com/watch?v=EBiC7S4A7go> WATCH THIS OR DIE
NOT RICKROLL I SWEAR <@!756564712589885503>

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
<#789662825215426568>

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
watch this 1 too <https://itshort.cf/ee265>

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
I did delete a bunch of stuff on the issue though ¯\_(ツ)_/¯

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
First comment 😛

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
😭

**Comment by Explosion-Scratch** [comment]
TheColaber wrote: 
 
hacker mode

**Comment by Explosion-Scratch** [comment]
The One Who Knocked wrote: 
 
how

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Cool right!

**Comment by Explosion-Scratch** [comment]
GrahamSH wrote: 
 
Does this work?

**Comment by GrahamSH-LLK** [comment]
Make it work the other way! (Like posts here go to discord)

**Comment by Explosion-Scratch** [comment]
GrahamSH wrote: 
 
Make it work the other way! (Like posts here go to github)
<@!756564712589885503>

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
Good idea!!

**Comment by Explosion-Scratch** [comment]
GrahamSH wrote: 
 
Thanks, but let's move to <#789662825215426568>

**Comment by Explosion-Scratch** [comment]
retronbv but alt wrote: 
 
Posty this explosion scratch

**Comment by Explosion-Scratch** [comment]
--Explosion-- wrote: 
 
It posted 😛

**Comment by Explosion-Scratch** [comment]
Touchcreator wrote: 
 
hi

**Comment by Explosion-Scratch** [comment]
Touchcreator wrote: 
 
but how, and why

**Comment by Explosion-Scratch** [comment]
thecoder876 wrote: 
 
Posty this explosion scratch

**Comment by Explosion-Scratch** [comment]
retronbv but alt wrote: 
 
Posty this explosion scratch

**Comment by Explosion-Scratch** [comment]
retronbv but alt wrote:

**Comment by Explosion-Scratch** [comment]
retronbv but alt wrote: 
 
<@!756564712589885503>  it doesnt do pictures

**Comment by Explosion-Scratch** [comment]
thecoder876 wrote: 
 
woah it works

**Comment by Explosion-Scratch** [comment]
thecoder876 wrote: 
 
https://github.com/Bijou-js/Bijou.js/issues/32

**Comment by Explosion-Scratch** [comment]
william27 wrote: 
 
where does this post

**Comment by Explosion-Scratch** [comment]
thecoder876 wrote: 
 
OHHHHH

**Comment by Explosion-Scratch** [comment]
thecoder876 wrote: 
 
This uses Zapier

**Comment by Explosion-Scratch** [comment]
retronbv but alt wrote: 
 
Duh

**Comment by Explosion-Scratch** [comment]
The One Who Knocked wrote: 
 
ummmmmmmmmmmmmmmmmmmmmmm

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
ummm

**Comment by Explosion-Scratch** [comment]
Test

**Comment by Explosion-Scratch** [comment]
Touchcreator wrote: 
 
hi

**Comment by Explosion-Scratch** [comment]
Ampersand wrote: 
 
hi

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
https://media.discordapp.net/attachments/800944800530300969/808516028090810379/image0.png

**Comment by Explosion-Scratch** [comment]
Xan wrote: 
 
huh

**Comment by Explosion-Scratch** [comment]
thecoder876 wrote: 
 
- - / - - - / . - . / . . . / - morse code

**Comment by Explosion-Scratch** [comment]
retronbv wrote: 
 
hi

**Comment by Explosion-Scratch** [comment]
Ampersand wrote: 
 
sick

**Comment by Explosion-Scratch** [comment]
BATHILLS wrote:
