### ISSUE TITLE
[Feature request] Less Exclamation Marks in README.md

### ISSUE THREAD

**Issue by MTM828** [Bijou-js/Bijou.js#42]
**Is your feature request related to a problem? Please describe.**
Um, yeah.

**Describe the solution you'd like**
Less exclamation marks please.

**Comment by MTM828** [comment]
Ha.
Sorry if this isn't very nice.

**Comment by Explosion-Scratch** [comment]
Okay! I'll think about removing them! Thanks for contributing! Don't worry! Your issue wasn't mean! Have a nice life! Just kidding! I'll remove the exclamation marks! A little less joy never hurt anyone!

**Comment by MTM828** [comment]
@Explosion-Scratch Ha, LOL. :P

**Comment by D1WK** [comment]
Yeah lol

**Comment by Explosion-Scratch** [comment]
Star da project @MTM828

**Comment by retronbv** [comment]
don’t ask for stars 🙄 
(p.s. star it :P)

**Comment by AwayFromKeyword** [comment]
> Star da project @MTM828


Well don't ask for stars
(well definitely yes)

**Comment by MTM828** [comment]
Sure. :)

**Comment by Explosion-Scratch** [comment]
Thank you XD

**Comment by Explosion-Scratch** [comment]
> don’t ask for stars 🙄
> (p.s. star it :P)

=|

**Comment by Explosion-Scratch** [comment]
@all-contributors add @MTM828 for suggestions

**Comment by Explosion-Scratch** [comment]
@all-contributors add @MTM828 for content

**Comment by Explosion-Scratch** [comment]
@all-contributors add @Explosion-Scratch for content ideas platform

**Comment by Explosion-Scratch** [comment]
@all-contributors add @pufferfish101007 for tool question test tutorial

**Comment by MTM828** [comment]
> @all-contributors add @MTM828 for content

Thx. :)

**Comment by retronbv** [comment]
🤣
