### ISSUE TITLE
Implementations of hard but useful functions

### ISSUE THREAD

**Issue by TheColaber** [Bijou-js/Bijou.js#66]
We need more useful everyday coder stuff. Here is a list of things I think it would be cool if it did.

- [ ] Record screen - Allow settings like, time, hotkeys, record camera, etc. and then save the recording as a blob
- [x] Allow downloading blobs
- [ ] Creating gifs out of multiple images
- [ ] Play only a part of a sound blob/url
- [x] MD to HTML
- [ ] Graph Maker
- [ ] ... more coming soon!

I think that one thing I really love about this project, is that it has a variety of different functions that are really useful.

**Comment by AmpersandGD** [comment]
This seems cool

**Comment by Explosion-Scratch** [comment]
lol we have some of those already:

- Downloading blobs: `_$.saveBlob(blob, "filename.txt")`
- MD to HTML: `_$.markdownToHTML`
- Recording screen is pretty niche, it's pretty simple to program though. Pretty much `navigator.mediaDevices.getDisplayMedia()`.
- Graph maker, nice idea but would also be pretty simple using canvas, not to mention the amount of customization needed to make it good.
- Create gifs from multiple images: Good idea.
- Play only part of a sound or blob. Interesting, but still pretty simple:
```js
audio.currentTime = 50;//In seconds
audio.play();
setTimeout(audio.pause, 50);//Pause in 50 seconds.
```

**Comment by Explosion-Scratch** [comment]
Sorry, I don't think we'll ever implement the ones that I didn't address in my previous comment. Closing!
