### ISSUE TITLE
Bijou should return a class

### ISSUE THREAD

**Issue by TheColaber** [Bijou-js/Bijou.js#67]
It would be cool if we could do `new Bijou()` so that way we could have things like this.initTime, etc.

**Comment by Explosion-Scratch** [comment]
Classes are usually unique, we never change anything in the source code, why not just do this:
```js
import * as lol from "https://unpkg.com/bijou.js";
console.log(lol.uuid());
```
And why `this`? That keyword makes things extremely confusing.

**Comment by AmpersandGD** [comment]
> Classes are usually unique, we never change anything in the source code, why not just do this:
> 
> ```js
> import * as lol from "https://unpkg.com/bijou.js";
> console.log(lol.uuid());
> ```
> 
> And why `this`? That keyword makes things extremely confusing.

for `t h i s` reason

**Comment by TheColaber** [comment]
> Classes are usually unique, we never change anything in the source code, why not just do this:
> 
> ```js
> import * as lol from "https://unpkg.com/bijou.js";
> console.log(lol.uuid());
> ```
> 
> And why `this`? That keyword makes things extremely confusing.

Not sure you know how classes actually work... anyway that's fine! Would just be useful if one would need to access multiple declarations, which could possibly lead to some cool stuff.

**Comment by Explosion-Scratch** [comment]
@TheColaber I probably don't =P

**Comment by GrahamSH-LLK** [comment]
I say that ``new Bijou()`` is overkill for the majority of what we do, especially considering that we want to be able to have users simply use it by including a script tag.

**Comment by Explosion-Scratch** [comment]
I agree with @GrahamSH-LLK, I don't think we'll implement this. Although `import functions from "bijou.js"` might be a viable option.
