### ISSUE TITLE
Site should be a different Repo

### ISSUE THREAD

**Issue by TheColaber** [Bijou-js/Bijou.js#68]
It's unorganized like this.

**Comment by AmpersandGD** [comment]
Seems correct, github pages could handle it.

**Comment by Explosion-Scratch** [comment]
Good idea, instead of doing that, I'll deploy from a folder and make a site folder, that way the people at js.org won't have to do anything.

**Comment by GrahamSH-LLK** [comment]
In progress with seperate repo.

**Comment by GrahamSH-LLK** [comment]
Moved to seperate repo, https://bijou.js.org is served from it.
