### ISSUE TITLE
[Feature request] We need a way to automate publishing packages like bijou.function

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#70]
All the packages, (while currently up to date) are going to be extremely hard to update manually. What is our solution to this?

**Comment by AmpersandGD** [comment]
> All the packages, (while currently up to date) are going to be extremely hard to update manually. What is our solution to this?

Honestly try finding a workflow in github marketplace to do that for you

**Comment by GrahamSH-LLK** [comment]
How about 
``const function = require('bijou.js).function``

**Comment by Explosion-Scratch** [comment]
@GrahamSH-LLK Nice idea! =) Then I can use the spread operator to combine them into temp!

**Comment by GrahamSH-LLK** [comment]
Or ``const { function } = require('bijou.js')``.
Honestly, we don't need separate packages. It's just a waste of time and space on npm.

**Comment by Explosion-Scratch** [comment]
@GrahamSH-LLK I deleted those packages!
