### ISSUE TITLE
 🤦🏻 [CRITICAL] Bijou throws error in node.js

### ISSUE THREAD

**Issue by Explosion-Scratch** [Bijou-js/Bijou.js#73]
```
SyntaxError: Unexpected token export
``` 
What do we do.

**Comment by AmpersandGD** [comment]
> ```
> SyntaxError: Unexpected token export
> ```
> 
> What do we do.

it ain't the end of the world, but we should try er......setting up a node.js workflow and retry? idk my mind is blank

**Comment by GrahamSH-LLK** [comment]
> > ```
> > SyntaxError: Unexpected token export
> > ```
> > 
> > 
> > What do we do.
> 
> it ain't the end of the world, but we should try er......setting up a node.js workflow and retry? idk my mind is blank

What?!? That makes no sense

**Comment by Explosion-Scratch** [comment]
Idkidkidk

**Comment by AmpersandGD** [comment]
> > > ```
> > > SyntaxError: Unexpected token export
> > > ```
> > > 
> > > 
> > > What do we do.
> > 
> > 
> > it ain't the end of the world, but we should try er......setting up a node.js workflow and retry? idk my mind is blank
> 
> What?!? That makes no sense

Well i thought we all understand that i'm the stupid one

**Comment by TheColaber** [comment]
Pretty sure it because of this:

https://github.com/Bijou-js/Bijou.js/blob/main/bijou.js#L4091

Try removing it and it might do away.

**Comment by TheColaber** [comment]
Hmm actually wait... it's because of how you build this... for example: 

https://github.com/Bijou-js/Bijou.js/blob/main/bijou.js#L117

Would probably be easier if you made one object and just exported that. Or maybe just used a class tbh.

**Comment by Explosion-Scratch** [comment]
Now using babel in `git.bat`
