### ISSUE TITLE
[Bug] syntaxHighlight errors

### ISSUE THREAD

**Issue by pufferfish101007** [Bijou-js/Bijou.js#81]
syntaxHighlight errors when there is text inside of style or script tags, or when highlighting css

**Comment by retronbv** [comment]
That is one long title there mr. gerbil

**Comment by retronbv** [comment]
fixed :)

**Comment by pufferfish101007** [comment]
> fixed :)

Where?

**Comment by Explosion-Scratch** [comment]
> > fixed :)
> 
> Where?

![image](https://user-images.githubusercontent.com/61319150/109303112-e8bd0680-77ff-11eb-810a-b151933c2566.png)

**Comment by retronbv** [comment]
> > > fixed :)
> > 
> > 
> > Where?
> 
> ![image](https://user-images.githubusercontent.com/61319150/109303112-e8bd0680-77ff-11eb-810a-b151933c2566.png)

I also edited the gerbil’s first message

**Comment by pufferfish101007** [comment]
Oh right I thought you meant you'd fixed the issue 🤪

**Comment by retronbv** [comment]
nope :p

**Comment by Explosion-Scratch** [comment]
@pufferfish101007 should we just remove this function altogether?

**Comment by pufferfish101007** [comment]
Probably yeah, especiallyconsidering some of it's from w3schools iirc. I'd waituntil you're doing other breaking changes as well tho so you don't have too many major versions 😆

**Comment by Explosion-Scratch** [comment]
Ok, removing now!
