### ISSUE TITLE
[Bug] beautifyJS doesn't beautify it very well

### ISSUE THREAD

**Issue by pufferfish101007** [Bijou-js/Bijou.js#83]
**Describe the bug**
There are a couple of issues, all with the lib - I'd suggest trying to find a better one or writing it ourselves.
- quotes are not escaped when they should be
- semicolons are not added

there are probably more.

**Comment by Explosion-Scratch** [comment]
XD Okay, this'd be a fun challenge to make, for now I'll just remove the function/
